# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1379197314);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.migration.version", 13);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.slowStartup.averageTime", 3566);
user_pref("browser.slowStartup.samples", 2);
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1379283713580");
user_pref("datareporting.policy.firstRunTime", "1379197313579");
user_pref("datareporting.sessions.current.activeTicks", 11);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2082);
user_pref("datareporting.sessions.current.main", 81);
user_pref("datareporting.sessions.current.sessionRestored", 2167);
user_pref("datareporting.sessions.current.startTime", "1379197541205");
user_pref("datareporting.sessions.current.totalTime", 56);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1379197312272,\"a\":4,\"t\":21,\"c\":true,\"m\":41,\"fp\":4028,\"sr\":4855}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"23.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\"},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"23.0\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\"},\"webapps-team@lists.launchpad.net\":{\"version\":\"2.4.6\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\"}}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:2.7,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2013.04.05.beta,online-accounts%40lists.launchpad.net:0.4.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"online-accounts@lists.launchpad.net\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"mtime\":1366823072000,\"rdfTime\":1353001206000}}},{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1379191549000,\"rdfTime\":1375741654000},\"webapps-team@lists.launchpad.net\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"mtime\":1366823072000,\"rdfTime\":1366057792000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"mtime\":1366823071000,\"rdfTime\":1365165782000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1379191489000,\"rdfTime\":1375560660000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1375562338000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1375562338000}}}]");
user_pref("extensions.lastAppVersion", "23.0");
user_pref("extensions.lastPlatformVersion", "23.0");
user_pref("extensions.pendingOperations", false);
user_pref("gecko.buildID", "20130803192641");
user_pref("gecko.mstone", "23.0");
user_pref("intl.charsetmenu.browser.cache", "windows-1252, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1379197541);
user_pref("toolkit.telemetry.previousBuildID", "20130803192641");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1381789318);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
